//
// Created by Alexander on 11.04.2026.
//

#ifndef CMAKESFMLPROJECT_GAMEPADMAPPINGDATASTRUCT_H
#define CMAKESFMLPROJECT_GAMEPADMAPPINGDATASTRUCT_H


class GamepadMappingDataStruct {

};


#endif //CMAKESFMLPROJECT_GAMEPADMAPPINGDATASTRUCT_H
