//
// Created by gorod on 10.04.2026.
//

#ifndef CMAKESFMLPROJECT_GLOBALCOMMANDSLISTENERSOBSERVERSINGLETON_H
#define CMAKESFMLPROJECT_GLOBALCOMMANDSLISTENERSOBSERVERSINGLETON_H


class GlobalCommandsListenersObserverSingleton {
};


#endif //CMAKESFMLPROJECT_GLOBALCOMMANDSLISTENERSOBSERVERSINGLETON_H