//
// Created by Alexander on 09.04.2026.
//

#ifndef CMAKESFMLPROJECT_GLOBALCOMMANDPREFIX_H
#define CMAKESFMLPROJECT_GLOBALCOMMANDPREFIX_H


enum class GlobalCommandPrefix {
    FORWARD, BACKWARD, LEFT, RIGHT, NOISE
};


#endif //CMAKESFMLPROJECT_GLOBALCOMMANDPREFIX_H
