//
// Created by Alexander on 09.04.2026.
//

#ifndef CMAKESFMLPROJECT_GLOBALCOMMANDPREFIX_H
#define CMAKESFMLPROJECT_GLOBALCOMMANDPREFIX_H


enum class GlobalCommandPrefix {
    MOVEMENT, ROTATION, NOISE_DIGITAL, NOISE_ANALOG, NO_DATA
//FORWARD, BACKWARD, LEFT, RIGHT, NOISE, NO_DATA


};


#endif //CMAKESFMLPROJECT_GLOBALCOMMANDPREFIX_H
