//
// Created by gorod on 10.04.2026.
//

#ifndef CMAKESFMLPROJECT_GLOBALCOMMANDSLISTENER_H
#define CMAKESFMLPROJECT_GLOBALCOMMANDSLISTENER_H


class GlobalCommandsListener {
};


#endif //CMAKESFMLPROJECT_GLOBALCOMMANDSLISTENER_H