//
// Created by Alexander on 09.04.2026.
//

#ifndef CMAKESFMLPROJECT_VEHICLECONSTANTS_H
#define CMAKESFMLPROJECT_VEHICLECONSTANTS_H

extern float MAX_FORWARD = 1;
extern float MAX_BACKWARD = -1;


#endif //CMAKESFMLPROJECT_VEHICLECONSTANTS_H
